r"""
src/installshim.py

Pure logic for the nameable-agent install verbs (Phase 36 / specs/0036).

Stdlib-only, side-effect-free: no filesystem, no PATH lookup, no clock, no sys.executable — EVERY input is
an argument. That is what keeps it unit-testable AND keeps `openagent-code --set-name` from importing
runtime/model/session (so it can run with no configured endpoint). The thin write side effects live in
cli._set_name / cli._remove_name; everything decided here is a pure function of its arguments.

The launcher MIRRORS scripts/oac.ps1 — a PowerShell `$PROFILE` function that calls the venv
`openagent-code.exe @args` — because on the reference machine `oac` is exactly that (a profile function,
not a file on PATH). `@args` also forwards shell metacharacters losslessly, unlike a .cmd.
"""
import os
import re
from collections import namedtuple

_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,31}$")

# Windows reserved DEVICE names (a file named CON/NUL/... is special). Matched case-insensitively, and a
# trailing dot / space or an extension does not un-reserve them (CON.txt is still CON).
_RESERVED = ({"con", "prn", "aux", "nul"}
             | {f"com{i}" for i in range(1, 10)}
             | {f"lpt{i}" for i in range(1, 10)})

# Names that collide with what already exists / the default identity — never a valid --set-name target.
_TAKEN = {"openagent-code", "oac"}

LauncherPlan = namedtuple("LauncherPlan", "path content chmod profile_line note")
RemovePlan = namedtuple("RemovePlan", "path profile_line")


def validate_name(name):
    """Return the validated launch/identity name, or raise ValueError. Conservative: the name becomes a
    FILENAME on PATH and a PowerShell function name, so anything unusual is rejected."""
    n = (name or "").strip()
    if not n:
        raise ValueError("a name is required")
    if not _NAME_RE.match(n):
        raise ValueError("use 1-32 chars: a letter, then letters/digits/'-'/'_' (no spaces, paths, or '..')")
    base = n.split(".")[0].strip().lower()   # CON.txt / 'nul ' still resolve to the reserved device
    if base in _RESERVED:
        raise ValueError(f"'{n}' is a reserved device name")
    if n.lower() in _TAKEN:
        raise ValueError(f"'{n}' is reserved (it is the default name / the existing command)")
    return n


def _upsert(lines, key, value):
    """Return `lines` with `key=value` set in place at the first assignment of key (else appended); a
    value of None removes every `key=` line. Untouched lines are preserved byte-for-byte."""
    prefix = key + "="
    out, done = [], False
    for ln in lines:
        if ln.strip().startswith(prefix):
            if value is None:
                continue                      # remove
            if not done:
                out.append(prefix + value)    # replace in place, once
                done = True
            continue                          # drop any duplicate assignment
        out.append(ln)
    if value is not None and not done:
        out.append(prefix + value)            # append when it was absent
    return out


def compute_env_update(env_text, name, persona):
    """Pure string->string edit of a .env body. Sets CODE_AGENT_NAME / CODE_AGENT_PERSONA in place (or
    appends), OMITS the persona line when persona is empty, and REMOVES both vars when `name` is falsy (the
    --remove-name revert to default). Preserves every untouched line and is idempotent (applying twice ==
    once). Newlines in persona are already stripped by the caller; strip defensively here too."""
    lines = env_text.split("\n")
    if not name:                                          # --remove-name: revert to default (OAC)
        lines = _upsert(lines, "CODE_AGENT_NAME", None)
        lines = _upsert(lines, "CODE_AGENT_PERSONA", None)
        return "\n".join(lines)
    per = (persona or "").replace("\n", " ").replace("\r", " ").strip()
    lines = _upsert(lines, "CODE_AGENT_NAME", name)
    lines = _upsert(lines, "CODE_AGENT_PERSONA", per if per else None)
    return "\n".join(lines)


def _ps_launcher(name, exe_path):
    """A PowerShell function mirroring scripts/oac.ps1, calling the venv openagent-code.exe with @args."""
    return (
        "# " + name + " - openagent-code launcher generated by --set-name (specs/0036). Safe to regenerate.\n"
        '$OacExe = "' + exe_path + '"\n'
        "function " + name + " {\n"
        "    if (-not (Test-Path $OacExe)) {\n"
        "        Write-Error \"openagent-code not found at $OacExe - run 'pip install -e .' first.\"\n"
        "        return\n"
        "    }\n"
        "    & $OacExe @args\n"
        "}\n"
    )


def plan_launcher(name, install_root, exe_path, python_exe, *, windows):
    """Return the LauncherPlan (path, content, chmod, profile_line, note) for creating a launcher named
    `name`. Windows: a scripts/<name>.ps1 function beside oac.ps1 (the operator dot-sources it in $PROFILE).
    POSIX: a <name> shell script in the venv bin dir (dirname(python_exe)) that execs the ABSOLUTE python
    with `-m src` (never a bare `python`). All inputs are arguments — no I/O, no sys.executable."""
    if windows:
        path = os.path.join(install_root, "scripts", name + ".ps1")
        profile_line = '. "' + path + '"'
        note = ("Add the line above to your PowerShell $PROFILE (notepad $PROFILE), then reload: . $PROFILE")
        return LauncherPlan(path, _ps_launcher(name, exe_path), None, profile_line, note)
    bin_dir = os.path.dirname(python_exe)
    path = os.path.join(bin_dir, name)
    content = "#!/bin/sh\nexec \"" + python_exe + "\" -m src \"$@\"\n"
    note = "Ensure " + bin_dir + " is on your PATH."
    return LauncherPlan(path, content, 0o755, None, note)


def plan_remove(name, install_root, *, windows):
    """Return the RemovePlan (launcher path + the $PROFILE line to remove) for `--remove-name`, mirroring
    plan_launcher's path/profile_line so a removal targets exactly what a set created."""
    if windows:
        path = os.path.join(install_root, "scripts", name + ".ps1")
        return RemovePlan(path, '. "' + path + '"')
    # POSIX bin dir isn't known without python_exe; the caller passes install_root's venv bin when it can.
    return RemovePlan(os.path.join(install_root, name), None)
